title: Helmsdeep.org
description: > # this means to ignore newlines until "baseurl:"
  An awesome description.
url: 'https://helmsdeep.github.io'
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->
markdown: kramdown
timezone: Australia/Brisbane
exclude: [vendor, 'Gemfile*']
gems: [jekyll-paginate, jekyll-feed]
paginate: 2
collections:
  authors:
    output: true
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  -
    scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
prose:
  rooturl: '_posts'
  siteurl: 'https://helmsdeep.github.io/'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
  metadata:
    _posts:
      - name: 'published'
        field:
          element: 'checkbox'
          value: true
          label: 'Published'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
      - name: 'author'
        field:
          element: 'select'
          label: 'Author'
          options: 'https://helmsdeep.github.io/authors.jsonp'
#            - name: None
#              value:
#            - name: Craig Holoak
#              value: craig
#            - name: Nathan Holoak
#              value: nathan
      - name: 'excerpt'
        field:
          element: 'textarea'
          label: 'Description'
          placeholder: 'Optional summary of the post'
