title: Helmsdeep.org
description: > # this means to ignore newlines until "baseurl:"
  An awesome description.
url: "http://www.helmsdeep.org"
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->
markdown: kramdown
timezone: Australia/Brisbane
exclude: [vendor, "Gemfile*"]
gems: [jekyll-paginate, jekyll-feed]
paginate: 2
#paginate_path: "/page:num"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



prose:
  rooturl: '_posts'
  siteurl: 'https://helmsdeep.github.io/'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
  metadata:
    _posts:
      - name: 'published'
        field:
          element: 'checkbox'
          value: true
          label: 'Published'
